spring.application.name=supermarket

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/supermarket_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
jwt.secret=${JWT_SECRET:c3VwZXJtYXJrZXRfc2VjcmV0X2tleV8yNTZiaXRzX2V4YW1wbGVfMTIzNDU2Nzg5}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Tắt Liquibase để tránh xung đột khi deploy cloud
spring.liquibase.enabled=false
# Hibernate tự động kiểm tra và tạo bảng nếu chưa có
spring.jpa.hibernate.ddl-auto=update

# Cấu hình logging level cho các package và class cụ thể
logging.level.com.api.supermarket=DEBUG
# Cấu hình logging level cho service và controller cụ thể
logging.level.com.api.supermarket.service = DEBUG
logging.level.com.api.supermarket.controller.LoggingTestController = TRACE
logging.file.name=logs/supermarket.log
# Cấu hình logging level cho Hibernate SQL để hiển thị câu lệnh SQL trong log
logging.level.org.hibernate.SQL=OFF
# Cấu hình logback để tạo file log theo ngày và nén file log cũ
logging.logback.rollingpolicy.file-name-pattern=logs/supermarket.%d{dd-MM-yyyy}.%i.log.gz
# Giới hạn kích thước file log, ví dụ: 10MB
logging.logback.rollingpolicy.max-file-size=10MB
# Giới hạn số lượng file log được lưu trữ, ví dụ: 30 file log
logging.logback.rollingpolicy.max-history=30
# Giới hạn tổng dung lượng log được lưu trữ, ví dụ: 1GB
logging.logback.rollingpolicy.total-size-cap=1GB 